### ISSUE TITLE
Don't provide a feature named 'test'

### ISSUE THREAD

**Issue by tarsius** [dickmao/nnreddit#25]
Melpa potentially excludes some "libraries" from the published package. But for people who install Emacs packages by cloning the Git repository instead of using `package.el` those libraries can be a problem.

The `test.el` "library" of this package is such a problematic case.

1. It should be named `nnreddit-tests.el` to avoid the potential of conflicts altogether.
2. It should not provide a feature at all. It is not a library that a user is going to load using `require` and it therefore does not need to provide a feature.
3. The feature/library name `test` is already used by the **package** named `test`.

Cheers!

**Comment by dickmao** [comment]
Right, thank you.
