### ISSUE TITLE
venv not installed when trying to open nnreddit:emacs

### ISSUE THREAD

**Issue by devinprater** [dickmao/nnreddit#32]
Specs:

MacBook Air Early 2015 running macOS Catilina 10.15 Public Beta 2
GNU Emacs 26.2 (build 1, x86_64-apple-darwin18.5.0, Carbon Version 158 AppKit 1671.4)
 of 2019-05-08
Copyright (C) 2019 Free Software Foundation, Inc.

Sorry if this is something obvious that I missed when installing, but this seems like a valid issue. I am a blind user, using Emacs along with Emacspeak for the best audible access to computing that I've ever not seen. :) I also use Reddit, although the website is crap and most mobile apps are too, which is why I'd love to use NNReddit.

So, I tried installing through Melpa first, and didn't find any hints on how to actually add a subreddit or anything in the Readme file on Github. I thought it didn't install correctly, because when in gnus, B didn't show the NNReddit backend.

So, I tried installing through make, and make install of the cloned git source, and I had to install a few Python packages to get this working, although it still gave an error, 255. So, I uninstalled the Melpa version, and restarted Emacs, and reinstalled it, restarting Emacs again. I then looked at an older NNReddit project, finding that I can do u, then nnreddit:emacs, at least in that version. So, I tried that, and it gave the following error:

nnreddit-venv: installing venv to nnreddit-20190710.1817-python...
 Invalid virtualenv specified!

So, is there anything else I need to get this working? I'm not a developer, just a user of Emacs because of Org-mode, Markdown support, darling in Python every now and then, Nov-mode, and hopefully Reddit. So, thanks for this Gnus backend, which hopefully will give me great access to Reddit.

**Comment by dickmao** [comment]
I uploaded to melpa a version of nnreddit that improves error diagnostics.  Please `M-x package-refresh-contents` and install version `20190712.1832`.  Then retry `M-x gnus`.

When you reproduce the venv error, the two buffers `*Shell Command Output*` and `*Messages*` should tell us what went wrong.

**Comment by devinprater** [comment]
Okay, I don’t have anything from a shell buffer, but I have this from *Messages*:
Checking new news...
Reading active file via nnreddit...
nnreddit-sentinel: process /Users/devinprater/.virtualenvs/nnreddit-20190712.1832-python/bin/python exited abnormally with code 1
 nnreddit-rpc-request: response timed out

So, right now, I have to use a VPN to access Reddit when at my current apartment. At work, this isn’t the case. Yes, it should be the opposite, and I won’t have to use a VPN for much longer. Because of that, though, using Pip doesn’t seem to work well when using the VPN, but I can access reddit.com <http://reddit.com/> from both Safari and EWW. Regarding the VEnv problem, I just had to do
Pip3 install virtual-env
Or something like that. macOS, and Homebrew, use python3 and pip3 instead of just python and pip.

So, hopefully the output of *Messages* helped.

**Comment by dickmao** [comment]
It *sounds* like the venv got installed okay.  To verify perhaps,
```
source /Users/devinprater/.virtualenvs/nnreddit-20190712.1832-python/bin/activate
python -c "import praw" && echo success
deactivate
```
If that checks out, and the proxy situation you mention is indeed a problem, you might try:
```
M-x customize-group RET nnreddit
Toggle "on" Nnreddit Log Rpc
```
Running gnus should now produce a valuable log in `/tmp/nnreddit-rpc-log.<yyyymmdd>.<hhmmss>`.

Additional diagnostics include:
```
M-x list-processes
Select Buffer " *nnreddit-default*"
Select Buffer " *nnreddit-default-stderr*"
```
and
```
M-x customize-group RET gnus-start
Set Gnus Verbose to 7 (Revert back to 5 for normal operation)
```

**Comment by devinprater** [comment]
Okay, I think I may have solved it. I set nnreddit to use Python3, deleted the virtual environment, restarted Emacs, ran Gnus, allowed Nnreddit to acmess my Reddit account, but now Emacs is doing who-knows-what and th… Oh, it just became responsive again, and it seems to have downloaded recent posts from all my subscribed subs, which is great because I thought I’d have to subscribe to them all over again. But, that took a good 3 minutes. Is that expected? Is there a way to make that less from now on?

**Comment by dickmao** [comment]
Three minutes is excessive.  Depending on network and server conditions, I experience a 4-8 second "grab cycle" per subscribed nnreddit on startup.  If you're subscribed to 20+ subreddits on a slow connection, then 3 minutes might be what it takes, unfortunately.

**Comment by dickmao** [comment]
I am closing this issue, as it seems the original venv issue is resolved.  Please feel free to continue asking questions here on this same thread, even though it's closed.
