### ISSUE TITLE
Note about travis + osx

### ISSUE THREAD

**Issue by purcell** [dickmao/nnreddit#50]
Hey, noticed you're using nix-emacs-ci, but preferring evm on osx. Did you encounter problems using nix-emacs-ci on both? It should work fine.

https://github.com/dickmao/nnreddit/blob/e61685aa7887b38d80e88336e0c2870890c3a62b/.travis.yml#L58

**Comment by dickmao** [comment]
#51 

Thanks.  For whatever reason I assumed it didn't apply to osx.
