### ISSUE TITLE
No address associated with hostname

### ISSUE THREAD

**Issue by mjakefranklin** [dickmao/nnreddit#56]
When attempting to run nnreddit after installing, I'm getting the following (copied from *Messages*):

```nntp (news) open error: ‘>>> (error news/nntp No address associated with hostname)’.  Continue? (y or n) y

Opening nntp server on news...

Server nntp+news previously determined to be down; not retrying

Opening nntp server on news...failed: >>> (error news/nntp No address associated with hostname)

Checking new news...

Reading active file from news via nntp...

Opening nntp server on news...

Server nntp+news previously determined to be down; not retrying

Opening nntp server on news...failed: >>> (error news/nntp No address associated with hostname)

Reading active file via nnreddit...

Opening nnreddit server...done

Reading active file via nnreddit...done

Checking new news...done

No news is good news

Warning: Opening nntp server on news...failed: >>> (error news/nntp No address associated with hostname); Server nntp+news previously determined to be down; not retrying; Opening nntp server on news...failed: >>> (error news/nntp No address associated with hostname); Server nntp+news previously determined to be down; not retrying

Auto-saving...done
```
Here's my config:

```
(use-package nnreddit
  :ensure t)

(add-to-list 'gnus-secondary-select-methods
             '(nnreddit ""))
```

After following the broad overview in the README, I'm unable to view any subreddit.  Is there something I missed?  I'm pretty new to gnus.  Thanks!

**Comment by dickmao** [comment]
> I'm pretty new to gnus

Gnus's default configuration is broken; that fact alone repels a wide swath of new users.  Those who bridge that initial gap still face an arduous uphill climb to useability.

Try the following in your config:
```
(use-package nnreddit :ensure t)
(custom-set-variables '(gnus-select-method (quote (nnreddit ""))))
```
If you're starting from a blank slate, the above should work better (the instructions you followed apply only to existing Gnus configs).  I've submitted a [patch to emacs-27](https://debbugs.gnu.org/cgi/bugreport.cgi?bug=37926) to de-"cluster" Gnus's longstanding "select method" confoundment.  It likely won't see the light of day for some time.

**Comment by mjakefranklin** [comment]
Interesting, no errors now after switching up the config.  Now I'm completely lost, but that's progress!  I'll do some more reading of the documentation for time being.

Curiously, when I try to view something via R g, I get:

```Wrong type argument:  stringp, nil```

**Comment by dickmao** [comment]
Please `M-: (setq debug-on-error t)` and `R g whatever` again to diagnose the null pointer exception.

**Comment by mjakefranklin** [comment]
Results:

```
Debugger entered--Lisp error: (wrong-type-argument stringp nil)
  string-match("^[^:]+:" nil)
  gnus-activate-group(nil t)
  nnreddit-goto-group("emacs")
  funcall-interactively(nnreddit-goto-group "emacs")
  call-interactively(nnreddit-goto-group nil nil)
  command-execute(nnreddit-goto-group)
```

**Comment by dickmao** [comment]
That's bad.  It means the [python backend](https://github.com/praw-dev/praw) didn't install correctly.

If you're still interested, you can try `M-: (venv-list-virtualenvs)` and confirm it's missing an entry for nnreddit.  Then you'd have to look at `*Messages*` for the string `nnreddit-venv` to see where it went wrong.

If not, I thank you for your interest in nnreddit.  I do actively maintain it, so it might become less fragile in the future.  Any information regarding why it didn't work out of the box would aid in that effort.

**Comment by mjakefranklin** [comment]
I was able to get much further this time.

Here's the result from ```*Messages*```:

```
nnreddit-venv: pip install exit 1
nnreddit-venv: installing venv to /home/jake/.virtualenvs/nnreddit-20191111.1431-python...
nnreddit-venv: There doesn’t appear to be a virtualenv executable on
    your exec path. Ensure that you have virtualenv installed and
    that the exec-path variable is set such that virtualenv can
    be found. A common cause of problems like this is GUI Emacs
    not having environment variables set up like the shell. Check
    out https://github.com/purcell/exec-path-from-shell for a
    robust solution to this problem.
```

This is a fresh Debian install, so I went ahead and did a ```sudo apt install python-pip python3-pip```, followed by a ```pip3 install virtualenv```, then added ~/.local/bin to my PATH.  Per the URL suggested at:

https://github.com/purcell/exec-path-from-shell

I added the following to my config:

```
(use-package exec-path-from-shell :ensure t)

(when (memq window-system '(mac ns x))
  (exec-path-from-shell-initialize))
```

Restarting Emacs gives the following:

```
nnreddit-venv: installing venv to /home/jake/.virtualenvs/nnreddit-20191111.1431-python...
Already using interpreter /usr/bin/python
New python executable in /home/jake/.virtualenvs/nnreddit-20191111.1431-python/bin/python
Installing setuptools, pip, wheel...
done.
Running virtualenv with interpreter /usr/bin/python
nnreddit-venv: installing venv to /home/jake/.virtualenvs/nnreddit-20191111.1431-python...done
```

Restarting and opening up gnus:

```
Opening nnreddit server...done
Opening nnreddit server...done
Opening nnfolder server on archive...done
No new newsgroups
Checking new news...
Reading active file via nnreddit...
Opening nnreddit server...done
nnreddit-sentinel: process /home/jake/.virtualenvs/nnreddit-20191111.1431-python/bin/python exited abnormally with code 1
nnreddit-rpc-call: nnreddit-rpc-request: response timed out
Reading active file via nnreddit...done
Checking new news...done
No news is good news
Warning: nnreddit-rpc-call: nnreddit-rpc-request: response timed out; nnreddit-sentinel: process /home/jake/.virtualenvs/nnreddit-20191111.1431-python/bin/python exited abnormally with code 1
```

**Comment by dickmao** [comment]
This is the problem: `nnreddit-sentinel: process /home/jake/.virtualenvs/nnreddit-20191111.1431-python/bin/python exited abnormally with code 1`

`M-x list-processes` might show an nnreddit-default-stderr entry, which you can RET on.  You might also try `M-: (switch-to-buffer " *nnreddit-default-stderr*")`.  Note the space preceding the buffer name.

You might try calling `/home/jake/.virtualenvs/nnreddit-20191111.1431-python/bin/python` from a bash prompt to ensure it's functional.

Finally, you can `M-x customize-group RET nnreddit` and toggle-on "Nnreddit Log Rpc".  Restart gnus and inspect `/tmp/nnreddit-rpc-log.timestamp` or wherever macOS puts temporary files.  For whatever reason the python backend is unhappy.

**Comment by mjakefranklin** [comment]
```M-x list-processes``` didn't show any entries.  However, the buffer you suggested showed the following:

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/jake/.emacs.d/elpa/nnreddit-20191111.1431/nnreddit/__main__.py", line 13, in <module>
    from .authenticated_reddit import AuthenticatedReddit
  File "/home/jake/.emacs.d/elpa/nnreddit-20191111.1431/nnreddit/authenticated_reddit.py", line 16, in <module>
    import praw
  File "/home/jake/.virtualenvs/nnreddit-20191111.1431-python/local/lib/python2.7/site-packages/praw-6.4.0-py2.7.egg/praw/__init__.py", line 14, in <module>
    from .reddit import Reddit  # NOQA
  File "/home/jake/.virtualenvs/nnreddit-20191111.1431-python/local/lib/python2.7/site-packages/praw-6.4.0-py2.7.egg/praw/reddit.py", line 2, in <module>
    import configparser
ImportError: No module named configparser

Process nnreddit-default stderr finished
```
I installed configparser via pip, now I'm stuck on:

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/jake/.emacs.d/elpa/nnreddit-20191111.1431/nnreddit/__main__.py", line 13, in <module>
    from .authenticated_reddit import AuthenticatedReddit
  File "/home/jake/.emacs.d/elpa/nnreddit-20191111.1431/nnreddit/authenticated_reddit.py", line 16, in <module>
    import praw
  File "/home/jake/.virtualenvs/nnreddit-20191111.1431-python/local/lib/python2.7/site-packages/praw-6.4.0-py2.7.egg/praw/__init__.py", line 14, in <module>
    from .reddit import Reddit  # NOQA
  File "/home/jake/.virtualenvs/nnreddit-20191111.1431-python/local/lib/python2.7/site-packages/praw-6.4.0-py2.7.egg/praw/reddit.py", line 26, in <module>
    from . import models
  File "/home/jake/.virtualenvs/nnreddit-20191111.1431-python/local/lib/python2.7/site-packages/praw-6.4.0-py2.7.egg/praw/models/__init__.py", line 3, in <module>
    from .front import Front
  File "/home/jake/.virtualenvs/nnreddit-20191111.1431-python/local/lib/python2.7/site-packages/praw-6.4.0-py2.7.egg/praw/models/front.py", line 2, in <module>
    from urllib.parse import urljoin
ImportError: No module named parse
```

**Comment by dickmao** [comment]
I wonder what `/home/jake/.virtualenvs/nnreddit-20191111.1431-python/bin/python --version` says.

In `/home/jake/.virtualenvs/nnreddit-20191111.1431-python/local/lib/python2.7/site-packages/praw-6.4.0-py2.7.egg/praw/compat.py`

```
if PY2:
    import ConfigParser as configparser  # noqa: F401
    from urlparse import urljoin, urlparse  # noqa: F401
else:
    import configparser  # noqa: F401
    from urllib.parse import urljoin, urlparse  # noqa: F401
```
One should not need go so far down into the weeds and install configparser or urllib.parse.  Sadly, either a bug in virtualenv or nnreddit seems to assume the executable `python` as version 2.7 even if perhaps in your latest version of debian `python` defaults to version 3.x.

One thing you can try is `M-x customize-group RET nnreddit` and explicitly set `Nnreddit Python Command` to python2 or python3.  Perhaps the explicit version designation will set virtualenv straight.

If that solves the problem, then I will need to fix things on my end to protect against this.

**Comment by mjakefranklin** [comment]
```/home/jake/.virtualenvs/nnreddit-20191111.1431-python/bin/python --version``` shows Python 2.6.16

Removing nnreddit from .virtualenv and setting either python2 or python3 directly stil l results in te same error unfortunately.

**Comment by dickmao** [comment]
Then, alas, I'm out of ideas.  For whatever reason, it's bypassing the PY2 branch in the code snippet above, and trying to import configparser and urljoin in the PY3 else-branch.

I'm sorry we couldn't make it work, but I thank you for your interest.  I'll eventually close this ticket unless you do it first.

**Comment by mjakefranklin** [comment]
No worries, I'll try messing with it later, but for now I'll close it.  Thanks again!

**Comment by dickmao** [comment]
In September, the [underlying python library] (https://github.com/praw-dev/praw) removed support for python 2.7.  I restricted the praw version that nnreddit uses to the [last version that still supports py27](https://github.com/dickmao/nnreddit/pull/61/commits/d4766182fa31f4d0e2e9bd7f9c64dd27d693d0e6#diff-2eeaed663bd0d25b7e608891384b7298).  You might try again if you're still curious.
