### ISSUE TITLE
cask unknown directive and --=-=-=--

### ISSUE THREAD

**Issue by torgeir** [dickmao/nnreddit#71]
This is more of a question than an issue, I guess;

I am getting `Unknown directive: (package-descriptor "lisp/nnreddit-pkg.el")` on os x 10.15 trying to make this package install.

```sh
[~/Code/nnreddit]$ make install                                                                   [master●]
/usr/local/bin/emacs -Q --batch --eval "(package-initialize)" --eval "(package-generate-autoloads \"nnreddit\" \"./lisp\")"
Package cl is deprecated
  INFO     Scraping files for nnreddit-autoloads.el...
  INFO     Scraping files for nnreddit-autoloads.el...done
pylint nnreddit

------------------------------------
Your code has been rated at 10.00/10

cask install
Unknown directive: (package-descriptor "lisp/nnreddit-pkg.el")
make: *** [test-compile] Error 255
```

```sh
[~/Code/nnreddit]$ cask --version                                                                  [master]
0.8.4
```

Why am I building it you ask - I was trying to debug this error that I get after adding nnreddit to gnus

```
Warning: nnreddit-sentinel: process /Users/torgeir/.virtualenvsnnreddit-20200417.1757-python/bin/python exited abnormally with code 127; nnreddit-rpc-call: Wrong type argument: stringp, nil
```

..which I since resolved by adding a trailing slash to `$WORKON_HOME` 🤦

**Comment by torgeir** [comment]
..which made it load as expected, but for some reason articles don't seem to load, and only renders `--=-=-=--`

<img width="882" alt="Screenshot 2020-05-24 at 11 17 10" src="https://user-images.githubusercontent.com/118202/82750403-30fe5280-9db0-11ea-932a-c63fe8df9885.png">

Rendering issues on os x? Suggestions where to go digging?

**Comment by dickmao** [comment]
> Unknown directive: (package-descriptor "lisp/nnreddit-pkg.el")

That is strange.  https://github.com/cask/cask/blob/master/cask.el#L429 is not consistent with that error.

I commited cb4ce17 to test MacOS in addition to Ubuntu, and [witnessed no such error](https://github.com/dickmao/nnreddit/runs/703997260?check_suite_focus=true#step:15:91).

As for --=-=-=--, what is `C-h v mm-text-html-renderer`.  And what is `M-: (fboundp 'libxml-parse-html-region)`?  It does seem the Simple HTML Renderer (shr) is not doing its job.

**Comment by dickmao** [comment]
Also, nnreddit can only be as fast as [PRAW](https://github.com/praw-dev/praw), the underlying backend which for good reason is duly throttled to protect Reddit.  While I've found nnreddit to be very usable with my current 3-4 low-traffic subreddits, it's not quite as tolerable with say 7-8 subreddits or a high-traffic subreddit like /r/funny.

**Comment by dickmao** [comment]
> since resolved by adding a trailing slash to $WORKON_HOME

Thanks for pointing out this bug 164e04f .

**Comment by torgeir** [comment]
dickmao <notifications@github.com> writes:

> Unknown directive: (package-descriptor "lisp/nnreddit-pkg.el")
>
> That is strange. https://github.com/cask/cask/blob/master/cask.el#L429 is not consistent with that error.
>
> I commited cb4ce17 to test MacOS in addition to Ubuntu, and witnessed no such error.

If that passes, I guess somethings fishy on my end..

> As for --=-=-=--, what is C-h v mm-text-html-renderer. And what is M-: (fboundp 'libxml-parse-html-region)? It does seem the Simple HTML Renderer (shr) is not doing its job.

`mm-text-html-renderer` is `shr` and `(fboundp
'libxml-parse-html-region)` is `t`.

**Comment by torgeir** [comment]
> .. very usable with my current 3-4 low-traffic subreddits, it's not
> quite as tolerable with say 7-8 subreddits or a high-traffic subreddit
> like /r/funny.

No worries, just playing around with this to learn more about gnus :)

**Comment by torgeir** [comment]
So, I removed emacs (I believe it was 27) and installed emacs-plus `brew install emacs-plus --HEAD ...` from master with emacs 28 and now it works 🤔

It installs a horde of dependencies, so some deps might well have been upgraded. Shr has been working fine for me in eww, tho

<img width="840" alt="Screenshot 2020-05-24 at 21 28 43" src="https://user-images.githubusercontent.com/118202/82763161-e90a1a80-9e05-11ea-8e6e-cfe541a7f152.png">

**Comment by dickmao** [comment]
> `mm-text-html-renderer` is `shr` and `(fboundp 'libxml-parse-html-region)` is `t`.

These were the correct answers.  :+1: 

While [the code is tested](https://github.com/dickmao/nnreddit/runs/704093256?check_suite_focus=true#step:13:17) on 28.0.50, I have less confidence in pre-release versions of emacs than 25.3 and 26.3.
