### ISSUE TITLE
Relationships between message / followup seems reverse

### ISSUE THREAD

**Issue by spiderbit** [dickmao/nnreddit#72]
with "/r" in gnus I should see the answeres to my posts as far as I understand:

> (gnus-summary-limit-to-replied &optional UNREPLIED)
> 
> Limit the summary buffer to replied articles.
> If UNREPLIED (the prefix), limit to unreplied articles.

instead I see the messages I ansered to:

So example:
1. somebody writes something
2. I answer it
3. the person responses back

I see then nr.1 instead of nr.3

**Comment by dickmao** [comment]
> 1. somebody writes something
> 2. I answer it
> 3. the person responses back
> 
> I see then nr.1 instead of nr.3

I think that's what whoever wrote `/r` intended -- "limit to replied" means show me messages to which I replied.

I think what you want is reddit's inbox semantics, "show me messages replying to me."

I added a special inbox newsgroup in 399c0a7.  One currently cannot reply directly from the inbox though, that would require additional code.
