### ISSUE TITLE
Did anybody use this with Emacs 27

### ISSUE THREAD

**Issue by spiderbit** [dickmao/nnreddit#73]
Not 100% sure if this module is the problem but I got some wrong datatype error, I thought my .newscr.eld is corrupted because I had to reboot the system without quiting gnus. So I tried old backups and stuff, but because I also had another problem with eshell, which I thought must be because of the emacs update I booted in my old version (nixos allows that) not only the eshell bug was gone but also gnus started again. It mentioned as last message trying to load a nnreddit group. And because the rest of gnus is included in Emacs I don't see how it's a gnus bug...

**Comment by dickmao** [comment]
Hey there.  As near as I can tell, no one uses this :laughing: 

When emacs27 released, I moved to it and have been nnreddit'ing on it ever since.

Without a minimum reproducible example yielding "wrong datatype," it's not practical for me to track this up.  Thanks for your interest.

**Comment by dickmao** [comment]
Ah, check that.  Emacs27 changed all obarrays to hash tables.  So one must byte-recompile all the nnreddit files when moving to emacs27.

**Comment by spiderbit** [comment]
ahh I got the message that I should bytecompile gnus which was strange, because that is in the system files.
