### ISSUE TITLE
Initial setup deadlocks EXWM

### ISSUE THREAD

**Issue by ieure** [dickmao/nnreddit#74]
It appears that the OAuth setup flow opens a web browser in a synchronous process, which blocks Emacs until the process terminates.  Since I use [EXWM](https://github.com/ch11ng/exwm), that means the click even on the Authorize button can't be processed (since Emacs is blocking on the process), and the process never terminates (because I cannot click either button).  This wedges Emacs until Firefox is killed from a terminal or SSH session.

I poked around the code, but I didn't see anything that looked like an obvious place this is happening.  I'm afraid nnreddit is blocking on a JSON-RPC request to the Python code, which is what's launching the browser, which seems like it might be harder to fix.

**Comment by dickmao** [comment]
Commit cf6bc58 should help.

Gnus is much reviled for blocking on fetch, and consequently takes EXWM down with it.  Gnus is ideally run with gnus-demon as a separate app much like Thunderbird.  EXWM is anathema to this.

**Comment by ieure** [comment]
Okay.  Is there a document that describes setting up OOB auth?

**Comment by dickmao** [comment]
No.  In cf6bc58^ (note the caret), gnus continues sitting on EXWM's control
thread (the gnus thread and your WM's thread are one and the same), and
thrashes on `nnreddit--mutex-rpc-request`.

In cf6bc58, gnus relinquishes control with an error.  The user presumably goes
about administering to "please check the browser."  If he can complete the oauth
dance in the browser, and if he knows how to operate gnus, he'll press "g" in
the *Group* buffer to manually refresh his feeds.
