### ISSUE TITLE
possible not to scan groups that are lower level than current?

### ISSUE THREAD

**Issue by unhammer** [dickmao/nnreddit#77]
I have default level 3, nnreddit groups on 4, but it still scans them on `gnus-group-restart` or `gnus-group-get-new-news` – is there a way to avoid scanning until I hit `L`?

**Comment by dickmao** [comment]
This ought to work:

`C-u 3 M-x gnus-group-get-new-news`

Otherwise, you'll have to custom-set-variable `gnus-activate-level`, which might have weird consequences.
