### ISSUE TITLE
nnreddit disables topic mode map

### ISSUE THREAD

**Issue by gdindi** [dickmao/nnreddit#80]
Hello,

When I use nnreddit, the bindings for topics in the group buffer are disabled. 

An example: usually, when in topic mode, M-g gets the news for all the groups in a topic, but when nnreddit is activated, M-g calls gnus-get-news-this-group instead of gnus-get-news-this-topic.

If I (unload-feature 'nnreddit) all topic mode bindings are available again.

I am using Emacs master branch.

Thanks.

**Comment by dickmao** [comment]
My bad, thanks.
