### ISSUE TITLE
Improve performance/don't fetch initial group list each time

### ISSUE THREAD

**Issue by Thaodan** [dickmao/nnreddit#86]
Hey, 

First of all thanks for your work.

I noticed that  the list of groups is fetched each time, e.g. where in for example nnimap only the list command is called but it does feel like nnreddit does more.

For example when open gnus nnreddit fetches all group no matter the group level, for example I have set all my nnreddit groups to 4 to not be fetched without a prefix of 4.

After the initial fetch when gnus was opened and `gnus-group-get-news` doesn't fetch the groups outside of the set minimum level as the group list isn't fetched.
This maybe a separate issue by itself if you want I can create another issue for that.

It would be useful if nnreddit would fetch the list of groups faster or reduce the data fetched (even nnntp is faster :/).

**Comment by dickmao** [comment]
You make a good point.  Commit 5a10f3f
